# https://cirrus-ci.com/github/burghardt/easy-wg-quick
test_task:
  name: FreeBSD test run
  freebsd_instance:
    matrix:
      image_family: freebsd-15-0-snap
      image_family: freebsd-14-1
      image_family: freebsd-13-3
  env:
    CIRRUS_CLONE_DEPTH: 10
  pkginstall_script:
    - pkg install -y net/wireguard-tools graphics/libqrencode
    - pkg install -y shells/bash devel/bats-core
  wg-quick_install_from_git_script:
    - fetch -o /usr/local/sbin/wg-quick https://raw.githubusercontent.com/WireGuard/wireguard-tools/master/src/wg-quick/freebsd.bash
    - chmod 0755 /usr/local/sbin/wg-quick
  kldload_if_wg_script:
    - kldload if_wg || true
  unittests_script:
    - cd tests && ./runtests.bash
  configure_script:
    - echo none > fwtype.txt
  1st_test_run_script:
    - ./easy-wg-quick
  2nd_test_run_script:
    - ./easy-wg-quick named_client
  dump_configuration_script:
    - head *.txt *.key *.conf
  dump_hub_configuration_script:
    - cat wghub.conf
  check_for_empty_files_script:
    - ls *.txt *.key *.conf | xargs -tn1 test -s
  setup_wireguard_interface_script:
    - wg-quick up ./wghub.conf
  check_interface_script:
    - ifconfig wghub
    - wg show
  teardown_wireguard_interface_script:
    - wg-quick down ./wghub.conf
